##关服提示
StopMessage: '&e服务器已关闭'

##是否开启公告
TimeMessage: true

##公告列表
TimeMessageList:
  - '&e欢迎使用橙汁插件'
  - '&c测试1'
  - '&a测试2'

##发送间隔时间,（单位:秒）
Time: 10

##是否开启聊天
Chat: true

##屏蔽词
AntiKeyWords:
  - 'cnm'
  - 'nmsl'
  - 'caonima'
  - 'nimasile'
  - 'noob'
  - 'fuck'
  - '渣渣'
  - '你妈'
  - '没妈'
  - '弱智'
  - '傻逼'
  - '孤儿'
  - '死妈'
  - '废物'
  - '智障'
  - '杂种'
  - '没脑子'
  - '弟弟'
  - '神经病'
  - '${'

##禁言列表
mutelist:
  - 'test'
