##关服提示
stopMessage: '&e服务器已关闭'

##是否开启聊天
Chat: true

##屏蔽词
AntiKeyWords:
  - 'cnm'
  - 'nmsl'
  - 'caonima'
  - 'nimasile'
  - 'noob'
  - 'fuck'
  - '渣渣'
  - '你妈'
  - '没妈'
  - '弱智'
  - '傻逼'
  - '孤儿'
  - '死妈'
  - '废物'
  - '智障'
  - '杂种'
  - '没脑子'
  - '弟弟'
  - '神经病'
  - '${'
